# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  # desc "Runs all the tests"
  # lane :test do
  #   Dir.chdir "../.." do
  #     sh("flutter", "packages", "get")
  #     sh("flutter", "test")
  #   end
  # end

  desc "Deploy a new beta build to Google Play"
  lane :beta do
    build_number = number_of_commits()
    puts "build number: #{build_number}"
    Dir.chdir "../.." do
      sh("flutter", "packages", "get")
      sh("flutter", "clean")
      sh("flutter", "build", "appbundle", "--build-number=#{build_number}")
    end
    upload_to_play_store(track: 'beta', aab: "../build/app/outputs/bundle/release/app-release.aab")  
  end
end
