# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:android)

  desc "Deploy a new beta build to Google Play"
  lane :beta do
    build_number = number_of_commits()
    Dir.chdir "../.." do
      sh("flutter", "packages", "get")
      sh("flutter", "clean")
      sh("flutter", "build", "appbundle", "--build-number=#{build_number+8}")
    puts "Build number: #{build_number}"
    end
    upload_to_play_store(track: 'beta', aab: "../build/app/outputs/bundle/release/app-release.aab")  
  end
